name: Benchmark scippneutron

on: 
  schedule:
    - cron: '0 * * * *'
  push:
  

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone Scipp Neutron
        shell: bash -l {0}
        run: git clone https://github.com/scipp/scippneutron repo
        
      - name: Check if commit already benched
        shell: bash -l {0}
        run: |
          export SCIPP_COMMIT_HASH="$(command git ls-remote https://github.com/scipp/scippneutron HEAD | head -n1 | sed -e 's/\s.*$//')"
          if grep -Fxl "$SCIPP_COMMIT_HASH" scipp_commit_hash; then exit 1; fi
          echo "$SCIPP_COMMIT_HASH" > scipp_commit_hash

      - name: Cache conda pkgs
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('repo/scipp-developer.yml') }}

      - name: Setup Mambaforge and Scipp Neutron dev env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: repo/scippneutron-developer.yml
          activate-environment: scippneutron-developer
          auto-activate-base: false

      - name: Install asv
        shell: bash -l {0}
        run: pip install asv

      - name: Configure asv
        shell: bash -l {0}
        run: asv machine --machine cloud-container --os "Ubuntu latest" --arch 'x86_64' --cpu "2 Core CPU" --num_cpu 2 --ram '7GB'

      - name: Run asv benchmarks
        shell: bash -l {0}
        run: |
          # Use mamba for env creation
          export CONDA_EXE=$(which mamba)
          asv run -v -m cloud-container -e

      - name: Commit changes and new results to github pages
        shell: bash -l {0}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add results/\*
          git add scipp_commit_hash
          git commit -m "[Bot] Update results"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Publish asv results locally
        shell: bash -l {0}
        run: asv publish

# Remove all but the website html folder, copy contents of html one higher, remove html,
# stash to revert main back to before cleaning, then git checkout gh_pages, before
# popping the stash and applying all changes for this branch.
      - name: Prep website for gh_pages branch
        shell: bash -l {0}
        run: |
          shopt -s extglob
          rm -v !("html") -rf -v
          cp -a ./html/* . -v
          rm -rf html -v
          rm -rf .github -v
          rm -rf .idea -v
          git add *
          git stash
          git fetch
          git checkout gh_pages
          git checkout stash -- .

      - name: Commit changes and new results to github pages
        shell: bash -l {0}
        run: |
          git add *
          git commit -m "[Bot] Publish to Github Pages"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh_pages
